export const projects = [
  {
    name: "Vivian",
    category: "AI COMPANION",
    color: "#d8bd88",
    colors: ["#24170e", "#957348", "#f2dcad"],
    orbitAngle: 0.88,
    radius: 0.6,
    kind: 1,
    rings: true,
    tagline: "A little company. A lot of heart.",
    description:
      "A cozy AI companion with Live2D, memory, voice, and vision. Vivian is my exploration of how technology can feel more personal, more present, and a little more human.",
    field: "Companion experience",
    status: "In development",
    tags: ["Live2D", "Memory", "Voice + vision"],
    href: "https://github.com/celestial-sora/ai-waifu",
    linkLabel: "Explore Vivian on GitHub",
  },
  {
    name: "Oonchai",
    category: "AI & STORYTELLING",
    color: "#b6514a",
    colors: ["#260b0e", "#7e2628", "#cd7160"],
    orbitAngle: 1.3,
    radius: 0.21,
    kind: 0,
    tagline: "A place for stories to become worlds.",
    description:
      "An AI roleplay platform for creating characters, exploring stories, and building conversations that remember you. Developed under the codename Sekaira, Oonchai gives imagination a place to stay.",
    field: "AI roleplay platform",
    status: "Live project",
    tags: ["Characters", "Memory", "Story worlds"],
    href: "https://oonchai.vercel.app/",
    linkLabel: "Enter Oonchai",
  },
  {
    name: "Vivian Qwen3 8B",
    title: "Vivian Qwen3",
    category: "8B LANGUAGE MODEL · V0.4",
    color: "#8bcbd6",
    colors: ["#102b40", "#6daec1", "#d1e9ed"],
    orbitAngle: 3.85,
    radius: 0.3,
    kind: 2,
    tagline: "A voice of her own, one conversation at a time.",
    description:
      "My fine-tuned Qwen3 8B language model, shared openly on Hugging Face. Version 0.4 includes the BF16 model weights, tokenizer, and chat template — ready to explore with Transformers.",
    field: "Qwen3 fine-tune",
    status: "Public · v0.4",
    tags: ["8B parameters", "BF16", "Apache 2.0"],
    href: "https://huggingface.co/celestial-sora/Vivian-Qwen3-8B-v0.4",
    linkLabel: "View model on Hugging Face",
  },
  {
    name: "Larp LLM",
    titleFont: "meme",
    category: "LANGUAGE MODEL PLAYGROUND",
    color: "#a08dbb",
    colors: ["#1b152c", "#695c80", "#c4b8d8"],
    orbitAngle: 2.7,
    orbitScale: 0.85,
    labelBelow: true,
    labelGap: 8,
    radius: 0.28,
    kind: 3,
    tagline: "An open playground for the next conversation.",
    description:
      "A Google Colab playground for my Larp LLM LoRA adapter, based on Gemma 3 12B. The notebook brings together Unsloth and Gradio to load the model and launch a temporary chat interface in a GPU runtime.",
    field: "Gemma 3 12B · LoRA",
    status: "Public repository",
    tags: ["Google Colab", "Unsloth", "Gradio"],
    href: "https://github.com/celestial-sora/Larp-LLM",
    linkLabel: "Explore Larp LLM on GitHub",
    links: [
      {
        label: "Open the Colab playground",
        href: "https://colab.research.google.com/github/celestial-sora/Larp-LLM/blob/main/Larp_LLM_Colab_Playground.ipynb",
      },
    ],
  },
  {
    name: "Sora",
    titleFont: "sweetbliss",
    category: "A LITTLE HELLO FROM ME",
    color: "#75c5b5",
    colors: ["#092b28", "#438f83", "#b4e5d4"],
    orbitAngle: 1.75,
    radius: 0.33,
    kind: 4,
    tagline: "A soft heart, a head full of daydreams, and a tiny universe to call home.",
    description:
      "hiii, i’m sora ♡ i make AI companions, little story worlds, and cozy places on the internet.\n\nthis is my little corner for things i dream up and slowly bring to life — a bit of code, a little curiosity, and lots of love.\n\nmake yourself comfy and have a little look around. i’m happy you found your way here (っ˘ω˘ς)",
    field: "AI · code · stories",
    status: "Always curious",
    tags: ["Independent creator", "Open source", "Sora Astral"],
    href: "https://github.com/celestial-sora",
    linkLabel: "come see what i’m making",
    links: [
      {
        label: "say hi to my AI creations ♡",
        href: "https://huggingface.co/celestial-sora",
      },
    ],
    social: true,
  },
];
